// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRegists(t *testing.T) {
	t.Parallel()

	query := Regists()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRegistsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRegistsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Regists().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRegistsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RegistSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRegistsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RegistExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Regist exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RegistExists to return true, but got false.")
	}
}

func testRegistsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	registFound, err := FindRegist(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if registFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRegistsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Regists().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRegistsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Regists().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRegistsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	registOne := &Regist{}
	registTwo := &Regist{}
	if err = randomize.Struct(seed, registOne, registDBTypes, false, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}
	if err = randomize.Struct(seed, registTwo, registDBTypes, false, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = registOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = registTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Regists().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRegistsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	registOne := &Regist{}
	registTwo := &Regist{}
	if err = randomize.Struct(seed, registOne, registDBTypes, false, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}
	if err = randomize.Struct(seed, registTwo, registDBTypes, false, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = registOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = registTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func registBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func registAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func registAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func registBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func registAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func registBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func registAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func registBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func registAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Regist) error {
	*o = Regist{}
	return nil
}

func testRegistsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Regist{}
	o := &Regist{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, registDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Regist object: %s", err)
	}

	AddRegistHook(boil.BeforeInsertHook, registBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	registBeforeInsertHooks = []RegistHook{}

	AddRegistHook(boil.AfterInsertHook, registAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	registAfterInsertHooks = []RegistHook{}

	AddRegistHook(boil.AfterSelectHook, registAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	registAfterSelectHooks = []RegistHook{}

	AddRegistHook(boil.BeforeUpdateHook, registBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	registBeforeUpdateHooks = []RegistHook{}

	AddRegistHook(boil.AfterUpdateHook, registAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	registAfterUpdateHooks = []RegistHook{}

	AddRegistHook(boil.BeforeDeleteHook, registBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	registBeforeDeleteHooks = []RegistHook{}

	AddRegistHook(boil.AfterDeleteHook, registAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	registAfterDeleteHooks = []RegistHook{}

	AddRegistHook(boil.BeforeUpsertHook, registBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	registBeforeUpsertHooks = []RegistHook{}

	AddRegistHook(boil.AfterUpsertHook, registAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	registAfterUpsertHooks = []RegistHook{}
}

func testRegistsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRegistsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(registColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRegistsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRegistsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RegistSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRegistsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Regists().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	registDBTypes = map[string]string{`ID`: `uuid`, `Name`: `text`}
	_             = bytes.MinRead
)

func testRegistsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(registPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(registAllColumns) == len(registPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, registDBTypes, true, registPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRegistsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(registAllColumns) == len(registPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Regist{}
	if err = randomize.Struct(seed, o, registDBTypes, true, registColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, registDBTypes, true, registPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(registAllColumns, registPrimaryKeyColumns) {
		fields = registAllColumns
	} else {
		fields = strmangle.SetComplement(
			registAllColumns,
			registPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RegistSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRegistsUpsert(t *testing.T) {
	t.Parallel()

	if len(registAllColumns) == len(registPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Regist{}
	if err = randomize.Struct(seed, &o, registDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Regist: %s", err)
	}

	count, err := Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, registDBTypes, false, registPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Regist struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Regist: %s", err)
	}

	count, err = Regists().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
